# Generated by Django 5.1.4 on 2025-01-03 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_name', models.CharField(max_length=100)),
                ('Recipe_description', models.TextField()),
                ('Recipe_ingridients', models.TextField()),
                ('Recipe_steps', models.TextField()),
                ('Recipe_yt_url', models.URLField(blank=True)),
                ('Recipe_image', models.ImageField(upload_to='recipe_images/')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
