# Generated by Django 5.1.4 on 2025-01-05 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Recipe_ingridients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Recipe_steps',
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='Base_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Base_app.recipe')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
